/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout.Alignment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.QuanLyChiTietHoiDong;
import dao.QuanLyHoiDong;
import dao.QuanLyKhoa;
import dao.QuanLyLoaiHoiDong;
import database.Database;
import entities.HoiDong;
import entities.Khoa;
import entities.LoaiHoiDong;
import gui_dialog.HoiDong_Dialog;

import javax.swing.JComboBox;
import javax.swing.JButton;
import java.awt.Color;

/**
 *
 * @author nmrhu
 */
public class HoiDong_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public HoiDong_Gui() {
		setSize(new Dimension(1500, 700));
		initComponents();

		DocDuLieuDatabaseVaoCombobox();
		DocDuLieuDatabaseVaoTable("", 0, null);
		clear();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlhd = new QuanLyHoiDong();
		qllhd = new QuanLyLoaiHoiDong();
		qlcthd = new QuanLyChiTietHoiDong();

		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBackground(Color.WHITE);
		jLabel1 = new javax.swing.JLabel();
		btnCapNhat = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnThem = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		txtTim = new javax.swing.JTextField();
		btnTim = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Danh mục / Hội đồng");

		btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
		btnCapNhat.setIcon(new javax.swing.ImageIcon("image/Update Left Rotation_30px.png")); // NOI18N
		btnCapNhat.setText("Cập nhật");
		btnCapNhat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				HoiDong_Dialog dialog = new HoiDong_Dialog(main, true);
				dialog.setTitle("Cập nhật hội đồng");
				dialog.setLocationRelativeTo(main);
				int kiemTraHoiDong = qlhd.tim_HoiDong_TrongPhieuDiem(hd.getMaHD());
				if (kiemTraHoiDong > 0) {
					JOptionPane.showMessageDialog(main, "Hội đồng đã được phân công nên không thể cập nhật");
					dialog.setData(3, hd);
				}
				else
					dialog.setData(2, hd);
				dialog.setVisible(true);
			}
		});

		btnXoa.setBackground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				xoaHoiDong();
				hd = null;
			}
		});

		btnThem.setBackground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new javax.swing.ImageIcon("image/add_30px.png")); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				HoiDong_Dialog dialog = new HoiDong_Dialog(main, true);
				dialog.setTitle("Thêm hội đồng");
				dialog.setLocationRelativeTo(main);
				dialog.setData(1, null);
				dialog.setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 344, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
						.addComponent(btnThem, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(btnCapNhat, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(btnCapNhat)
										.addComponent(btnXoa).addComponent(btnThem))
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		jPanel3.setLayout(jPanel3Layout);

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Hội đồng", "Loại hội đồng", "Ngày lập" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTable1.setModel(dm);
		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				int row = jTable1.getSelectedRow();
				TableModel model = jTable1.getModel();
				String maHD = model.getValueAt(row, 0).toString();
				hd = qlhd.chiTietHoiDong(Integer.parseInt(maHD));

				btnCapNhat.setEnabled(true);
				btnXoa.setEnabled(true);
			}
		});
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setRowHeight(40);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18NjScrollPane1.setViewportView(jTable1);
		jScrollPane1.setViewportView(jTable1);

		btnTim.setBackground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new javax.swing.ImageIcon("image/search_30px.png")); // NOI18N
		btnTim.setText("Tìm");
		btnTim.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String txt = txtTim.getText();
				DocDuLieuDatabaseVaoTable(txt, 0, null);
			}
		});

		cbbLHD = new JComboBox<LoaiHoiDong>();

		JButton btnLoc = new JButton();
		btnLoc.setText("Lọc");
		btnLoc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				LoaiHoiDong lhd = (LoaiHoiDong) cbbLHD.getSelectedItem();
				DocDuLieuDatabaseVaoTable("", 1, lhd);
				txtTim.setText("");
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(
				Alignment.TRAILING,
				jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(Alignment.TRAILING)
						.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
								.addComponent(cbbLHD, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(btnLoc, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(
						jPanel4Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
										.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(txtTim, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnTim)
												.addComponent(cbbLHD, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnLoc, GroupLayout.PREFERRED_SIZE, 39,
														GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
										.addContainerGap()));
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
						.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(18).addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}

	public void xoaHoiDong() {
		int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa " + hd.getMaHD() + " không ?", "Chú ý",
				JOptionPane.YES_NO_OPTION);
		if (hoi == JOptionPane.YES_OPTION) {
			try {
				qlcthd.delete_CTHD_HoiDong(hd.getMaHD());
				qlhd.delete(hd.getMaHD());

				DocDuLieuDatabaseVaoTable("", 0, null);
				clear();
				JOptionPane.showMessageDialog(this, "Xóa thành công ");
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(this, "Hội đồng không thể xóa!");
			}
		}
	}

	public void XoaHetDuLieuTrenCombobox() {
		DefaultComboBoxModel<LoaiHoiDong> dm = (DefaultComboBoxModel<LoaiHoiDong>) cbbLHD.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<LoaiHoiDong> list = new ArrayList<LoaiHoiDong>();
		qllhd = new QuanLyLoaiHoiDong();
		list = qllhd.dsLoaiHoiDong();

		DefaultComboBoxModel<LoaiHoiDong> dm = (DefaultComboBoxModel<LoaiHoiDong>) cbbLHD.getModel();
		for (LoaiHoiDong lhd : list) {
			dm.addElement(lhd);
		}
	}

	public void DocDuLieuDatabaseVaoTable(String txt, int tim, LoaiHoiDong lhd) {
		dm = (DefaultTableModel) jTable1.getModel();
		dm.setRowCount(0);
		List<HoiDong> list = new ArrayList<HoiDong>();
		qlhd = new QuanLyHoiDong();
		if (tim == 1) {
			list = qlhd.tim_HoiDong_Loai(lhd.getMaLHD());
		} else {
			if (txt.equals(""))
				list = qlhd.dsHoiDong();
			else
				list = qlhd.tim_HoiDong(txt);
		}

		for (HoiDong hd : list) {
			LoaiHoiDong lhoidong = qllhd.chiTietLoaiHoiDong(hd.getLoaiHoiDong().getMaLHD());
			dm.addRow(new Object[] { hd.getMaHD(), lhoidong.getTenLHD(), hd.getNgayLap() });
		}
	}

	public void clear() {
		btnXoa.setEnabled(false);
		btnCapNhat.setEnabled(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnCapNhat;
	private javax.swing.JButton btnXoa;
	private javax.swing.JButton btnThem;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JComboBox<LoaiHoiDong> cbbLHD;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtTim;
	private javax.swing.table.DefaultTableModel dm;

	private QuanLyChiTietHoiDong qlcthd;
	private QuanLyHoiDong qlhd;
	private QuanLyLoaiHoiDong qllhd;
	private HoiDong hd;

	public static Main main;
}
