/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.QuanLyGiangVien;
import dao.QuanLyKhoa;
import dao.QuanLyLuanVan;
import database.Database;
import entities.GiangVien;
import entities.Khoa;
import entities.LuanVan;
import gui_dialog.Khoa_Dialog;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

/**
 *
 * @author nmrhu
 */
public class Khoa_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public Khoa_Gui() {
		setSize(new Dimension(1500, 700));
		initComponents();

		DocDuLieuDatabaseVaoTable("");
		clear();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();

		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBackground(Color.WHITE);
		jLabel1 = new javax.swing.JLabel();
		btnCapNhat = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnThem = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		txtTim = new javax.swing.JTextField();
		btnTim = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Danh mục / Khoa");

		btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
		btnCapNhat.setIcon(new javax.swing.ImageIcon("image/Update Left Rotation_30px.png")); // NOI18N
		btnCapNhat.setText("Cập nhật");
		btnCapNhat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Khoa_Dialog dialog = new Khoa_Dialog(main, true);
				dialog.setTitle("Cập nhật khoa");
				dialog.setLocationRelativeTo(main);
				dialog.setData(2, khoa);
				dialog.setVisible(true);
			}
		});

		btnXoa.setBackground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				xoaKhoa();
				khoa = null;
			}
		});

		btnThem.setBackground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new javax.swing.ImageIcon("image/add_30px.png")); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Khoa_Dialog dialog = new Khoa_Dialog(main, true);
				dialog.setTitle("Thêm khoa");
				dialog.setLocationRelativeTo(main);
				dialog.setData(1, null);
				dialog.setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnXoa,
								javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnCapNhat).addComponent(btnXoa).addComponent(btnThem))
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Khoa", "Tên khoa", "Website", "SĐT", "Email" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTable1.setModel(dm);
		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				int row = jTable1.getSelectedRow();
				TableModel model = jTable1.getModel();
				String maKhoa = model.getValueAt(row, 0).toString();
				khoa = qlkhoa.chiTietKhoa(Integer.parseInt(maKhoa));

				btnCapNhat.setEnabled(true);
				btnXoa.setEnabled(true);
			}
		});
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setRowHeight(40);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
		jScrollPane1.setViewportView(jTable1);

		btnTim.setBackground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new javax.swing.ImageIcon("image/search_30px.png")); // NOI18N
		btnTim.setText("Tìm");
		btnTim.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String txt = txtTim.getText();
				if (txt.equalsIgnoreCase("")) {
					DocDuLieuDatabaseVaoTable("");
				} else {
					DocDuLieuDatabaseVaoTable(txt);
				}
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel4Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnTim))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE).addContainerGap()));
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1198,
										Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(18).addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	public void xoaKhoa() {
		int hoi = JOptionPane.showConfirmDialog(this,
				"Bạn có chắc chắn xóa " + khoa.getMaKhoa() + " - " + khoa.getTenKhoa() + " không ?", "Chú ý",
				JOptionPane.YES_NO_OPTION);
		if (hoi == JOptionPane.YES_OPTION) {
			try {
				qlkhoa.delete(khoa.getMaKhoa());
				DocDuLieuDatabaseVaoTable("");
				main.lv_gui.DocDuLieuDatabaseVaoCombobox();
				main.sv_gui.DocDuLieuDatabaseVaoCombobox();
				main.gv_gui.DocDuLieuDatabaseVaoCombobox();
				clear();
				JOptionPane.showMessageDialog(this, "Xóa thành công ");
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(this, "Xóa không thành công ");
			}
		}
	}

	public void DocDuLieuDatabaseVaoTable(String txt) {
		dm = (DefaultTableModel) jTable1.getModel();
		dm.setRowCount(0);
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();

		if (txt.equals(""))
			list = qlkhoa.dsKhoa();
		else {
			list = qlkhoa.tim_Khoa(txt);
		}
		for (Khoa k : list) {
			dm.addRow(new Object[] { k.getMaKhoa(), k.getTenKhoa(), k.getWebsite(), k.getSdt(), k.getemail() });
		}
	}

	public void clear() {
		btnCapNhat.setEnabled(false);
		btnXoa.setEnabled(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnCapNhat;
	private javax.swing.JButton btnXoa;
	private javax.swing.JButton btnThem;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtTim;
	private javax.swing.table.DefaultTableModel dm;

	private QuanLyKhoa qlkhoa;
	public static Main main;
	public static Khoa khoa;
	// End of variables declaration//GEN-END:variables
}
