/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.QuanLyGiangVien;
import dao.QuanLyHocKy;
import dao.QuanLyKhoa;
import dao.QuanLyLuanVan;
import dao.QuanLySinhVien;
import database.Database;
import entities.GiangVien;
import entities.HocKy;
import entities.Khoa;
import entities.LuanVan;
import entities.SinhVien;
import gui_dialog.LuanVan_Dialog;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;

/**
 *
 * @author nmrhu
 */
public class LuanVan_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public LuanVan_Gui() {
		setSize(new Dimension(1500, 700));
		initComponents();

		DocDuLieuDatabaseVaoCombobox();
		DocDuLieuDatabaseVaoComboboxHocKy();
		DocDuLieuDatabaseVaoTable("", 0, null, null);
		clear();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();
		qlgv = new QuanLyGiangVien();
		qllv = new QuanLyLuanVan();
		qlhk = new QuanLyHocKy();

		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBackground(Color.WHITE);
		jLabel1 = new javax.swing.JLabel();
		btnCapNhat = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnThem = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		txtTim = new javax.swing.JTextField();
		btnTim = new javax.swing.JButton();
		cbbKhoa = new javax.swing.JComboBox<>();
		btnLoc = new javax.swing.JButton();

		setBackground(Color.WHITE);

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Danh mục / Luận văn");

		btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
		btnCapNhat.setIcon(new javax.swing.ImageIcon("image/Update Left Rotation_30px.png")); // NOI18N
		btnCapNhat.setText("Cập nhật");
		btnCapNhat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				LuanVan_Dialog dialog = new LuanVan_Dialog(main, true);
				dialog.setTitle("Cập nhật luận văn");
				dialog.setLocationRelativeTo(main);
				dialog.setData(2, lv);
				dialog.setVisible(true);
			}
		});

		btnXoa.setBackground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				xoaLuanVan();
				lv = null;
			}
		});

		btnThem.setBackground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new javax.swing.ImageIcon("image/add_30px.png")); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				LuanVan_Dialog dialog = new LuanVan_Dialog(main, true);
				dialog.setTitle("Thêm luận văn");
				dialog.setLocationRelativeTo(main);
				dialog.setData(1, null);
				dialog.setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnXoa,
								javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnCapNhat).addComponent(btnXoa).addComponent(btnThem))
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã luận văn", "Tên luận văn", "Giảng viên hướng dẫn", "Số lượng đăng ký", "Khoa", "Học kỳ" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTable1.setModel(dm);
		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				int row = jTable1.getSelectedRow();
				TableModel model = jTable1.getModel();
				String maLV = model.getValueAt(row, 0).toString();
				lv = qllv.chiTietLuanVan(Integer.parseInt(maLV));

				btnCapNhat.setEnabled(true);
				btnXoa.setEnabled(true);
			}
		});
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setRowHeight(40);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
		jScrollPane1.setViewportView(jTable1);

		btnTim.setBackground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new javax.swing.ImageIcon("D:\\image\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm");
		btnTim.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String txt = txtTim.getText();
				if (txt.equalsIgnoreCase("")) {
					DocDuLieuDatabaseVaoTable("", 0, null, null);
				} else {
					DocDuLieuDatabaseVaoTable(txt, 0, null, null);
				}
			}
		});

		DefaultComboBoxModel<Khoa> dmCbb = new DefaultComboBoxModel<Khoa>();
		cbbKhoa.setModel(dmCbb);

		cbbHK = new JComboBox<HocKy>();
		DefaultComboBoxModel<HocKy> dmHK = new DefaultComboBoxModel<HocKy>();
		cbbHK.setModel(dmHK);

		btnLoc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Khoa k = (Khoa) cbbKhoa.getSelectedItem();
				HocKy hk = (HocKy) cbbHK.getSelectedItem();
				DocDuLieuDatabaseVaoTable("", 1, k, hk);
			}
		});

		btnLoc.setIcon(new javax.swing.ImageIcon("D:\\image\\Mail Filter_30px.png")); // NOI18N
		btnLoc.setText("Lọc");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel4Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1436, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
								.addComponent(cbbHK, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(cbbKhoa, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(btnLoc, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(cbbKhoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(btnLoc).addComponent(cbbHK, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(btnTim)))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE).addContainerGap()));
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1198,
										Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(18).addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	public void xoaLuanVan() {
		int hoi = JOptionPane.showConfirmDialog(this,
				"Bạn có chắc chắn xóa " + lv.getMaLV() + " - " + lv.getTenLV() + " không ?", "Chú ý",
				JOptionPane.YES_NO_OPTION);
		if (hoi == JOptionPane.YES_OPTION) {
			try {
				qllv.delete(lv.getMaLV());
				DocDuLieuDatabaseVaoTable("", 0, null, null);
				clear();
				JOptionPane.showMessageDialog(this, "Xóa thành công ");
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(this, "Luận văn đã được đăng ký. Không thể xóa!");
			}
		}
	}

	public void XoaHetDuLieuTrenCombobox() {
		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();
		list = qlkhoa.dsKhoa();

		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		for (Khoa khoa : list) {
			dm.addElement(khoa);
		}
	}

	public void XoaHetDuLieuTrenComboboxHocKy() {
		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxHocKy() {
		XoaHetDuLieuTrenComboboxHocKy();
		List<HocKy> list = new ArrayList<HocKy>();
		qlhk = new QuanLyHocKy();
		list = qlhk.dsHocKy();

		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK.getModel();
		for (HocKy hk : list) {
			dm.addElement(hk);
		}
	}

	public void DocDuLieuDatabaseVaoTable(String txt, int timTheo, Khoa k, HocKy hk) {
		dm = (DefaultTableModel) jTable1.getModel();
		dm.setRowCount(0);
		List<LuanVan> list = new ArrayList<LuanVan>();
		qllv = new QuanLyLuanVan();

		if (timTheo == 1) {
			list = qllv.tim_LuanVanTheoKhoa(k.getMaKhoa(), hk.getMaHK());
		} else {
			if (txt.equals(""))
				list = qllv.dsLuanVan();
			else {
				list = qllv.tim_LuanVan(txt);
			}
		}

		for (LuanVan lv : list) {
			Khoa khoa = qlkhoa.chiTietKhoa(lv.getKhoa().getMaKhoa());
			GiangVien gv = qlgv.chiTietGiangVien(lv.getGiangVien().getMaGV());
			HocKy hocKy = qlhk.chiTietHocKy(lv.getHocKy().getMaHK());
			dm.addRow(new Object[] { lv.getMaLV(), lv.getTenLV(), gv.getHoTen(), lv.getSoLuongDk(), khoa.getTenKhoa(),
					hocKy.getTenHK() });
		}
	}

	public void clear() {
		btnCapNhat.setEnabled(false);
		btnXoa.setEnabled(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnCapNhat;
	private javax.swing.JButton btnXoa;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnLoc;
	private javax.swing.JComboBox<Khoa> cbbKhoa;
	private javax.swing.JComboBox<HocKy> cbbHK;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtTim;
	private javax.swing.table.DefaultTableModel dm;

	private QuanLyLuanVan qllv;
	private QuanLyGiangVien qlgv;
	private QuanLyKhoa qlkhoa;
	private QuanLyHocKy qlhk;

	public static Main main;

	public static LuanVan lv;
}
