/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import dao.QuanLySinhVien;
import dao.QuanLyTaiKhoan;
import database.Database;
import entities.SinhVien;
import entities.TaiKhoan;
import gui_dialog.DangNhap_Dialog;
import gui_dialog.DoiMatKhau_Dialog;
import gui_dialog.HocKy_Dialog;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dimension;
import java.awt.BorderLayout;

/**
 *
 * @author nmrhu
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();

		khoiTao();
		dangXuat();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor_fold defaultstate="collapsed" desc="Generated
	// Code">//GEN_BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlsv = new QuanLySinhVien();

		jPanel1 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel4.setForeground(Color.WHITE);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(15, 16, 422, 22);
		jMenuBar1 = new javax.swing.JMenuBar();
		HeThong = new javax.swing.JMenu();
		HeThong.setBackground(Color.WHITE);
		HeThong.setFont(new Font("Segoe UI", Font.PLAIN, 26));
		mnDangNhap = new javax.swing.JMenuItem();
		mnDoiMatKhau = new javax.swing.JMenuItem();
		mnTaiKhoan = new javax.swing.JMenuItem();
		mnThongTin = new javax.swing.JMenuItem();
		mnThongTin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				doiManHinh(tt_gui);
			}
		});
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		mnDangXuat = new javax.swing.JMenuItem();
		mnDangXuat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				dangXuat();
			}
		});
		mnThoat = new javax.swing.JMenuItem();
		mnThoat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				System.exit(0);
			}
		});
		DanhMuc = new javax.swing.JMenu();
		DanhMuc.setBackground(Color.WHITE);
		DanhMuc.setFont(new Font("Segoe UI", Font.PLAIN, 26));
		mnLuanVan = new javax.swing.JMenuItem();
		mnSinhVien = new javax.swing.JMenuItem();
		mnGiangVien = new javax.swing.JMenuItem();
		mnHoiDong = new javax.swing.JMenuItem();
		mnKhoa = new javax.swing.JMenuItem();
		mnKhoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				doiManHinh(khoa_gui);
			}
		});
		XuLy = new javax.swing.JMenu();
		XuLy.setBackground(Color.WHITE);
		XuLy.setFont(new Font("Segoe UI", Font.PLAIN, 26));
		mnDKLV = new javax.swing.JMenuItem();
		mnNhapDiem = new javax.swing.JMenuItem();
		mnNhapDiem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				nd_gui = new NhapDiem_Gui();
				doiManHinh(nd_gui);
			}
		});
		mnPhanCong = new javax.swing.JMenuItem();
		mnPhanCong.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				pc_gui = new PhanCong_Gui();
				doiManHinh(pc_gui);
			}
		});
		ThongKe = new javax.swing.JMenu();
		ThongKe.setBackground(Color.WHITE);
		ThongKe.setFont(new Font("Segoe UI", Font.PLAIN, 26));
		mnTK_Diem = new javax.swing.JMenuItem();
		mnTK_Diem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				doiManHinh(tklv_gui);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setExtendedState(JFrame.MAXIMIZED_BOTH);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setAutoscrolls(true);
		jPanel1.setPreferredSize(new Dimension(1500, 700));
		jPanel1.setLayout(new java.awt.BorderLayout());
		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel4.setBackground(new java.awt.Color(102, 204, 255));
		jPanel4.setPreferredSize(new java.awt.Dimension(1228, 50));

		jLabel1.setFont(new Font("Tahoma", Font.BOLD, 20)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Hệ thống quản lý luận văn tốt nghiệp");

		txtTaiKhoan = new JLabel();
		txtTaiKhoan.setBounds(1178, 16, 307, 22);
		txtTaiKhoan.setForeground(Color.WHITE);
		txtTaiKhoan.setFont(new Font("Tahoma", Font.BOLD, 18));

		getContentPane().add(jPanel4, BorderLayout.SOUTH);
		jPanel4.setLayout(null);
		jPanel4.add(jLabel1);
		jPanel4.add(txtTaiKhoan);

		jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
		jMenuBar1.setEnabled(false);

		HeThong.setIcon(new javax.swing.ImageIcon("image/gear_60px.png")); // NOI18N
		HeThong.setText("Hệ thống");

		mnDangNhap.setIcon(new javax.swing.ImageIcon("image/login_60px.png")); // NOI18N
		mnDangNhap.setText("Đăng nhập");
		mnDangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DangNhapActionPerformed(evt);
			}
		});
		HeThong.add(mnDangNhap);

		mnDoiMatKhau.setIcon(new javax.swing.ImageIcon("image/locked_with_key_60px.png")); // NOI18N
		mnDoiMatKhau.setText("Đổi mật khẩu");
		mnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DoiMatKhauActionPerformed(evt);
			}
		});
		HeThong.add(mnDoiMatKhau);

		mnTaiKhoan.setIcon(new javax.swing.ImageIcon("image/user_group_skin_type_7_60px.png")); // NOI18N
		mnTaiKhoan.setText("Quản lý tài khoản");
		mnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		HeThong.add(mnTaiKhoan);

		mnThongTin.setIcon(new javax.swing.ImageIcon("image/info_60px.png")); // NOI18N
		mnThongTin.setText("Thông tin");
		HeThong.add(mnThongTin);
		HeThong.add(jSeparator1);

		mnDangXuat.setIcon(new javax.swing.ImageIcon("image/export_60px.png")); // NOI18N
		mnDangXuat.setText("Đăng xuất");
		HeThong.add(mnDangXuat);

		mnThoat.setIcon(new javax.swing.ImageIcon("image/shutdown_60px.png")); // NOI18N
		mnThoat.setText("Thoát");
		HeThong.add(mnThoat);

		jMenuBar1.add(HeThong);

		DanhMuc.setIcon(new javax.swing.ImageIcon("image/list_60px.png")); // NOI18N
		DanhMuc.setText("Danh mục");

		mnLuanVan.setIcon(new javax.swing.ImageIcon("image/Page_60px.png")); // NOI18N
		mnLuanVan.setText("Luận văn");
		mnLuanVan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		DanhMuc.add(mnLuanVan);

		mnSinhVien.setIcon(new javax.swing.ImageIcon("image/student_male_60px.png")); // NOI18N
		mnSinhVien.setText("Sinh viên");
		mnSinhVien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		DanhMuc.add(mnSinhVien);

		mnGiangVien.setIcon(new javax.swing.ImageIcon("image/teacher_60px.png")); // NOI18N
		mnGiangVien.setText("Giảng viên");
		mnGiangVien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		DanhMuc.add(mnGiangVien);

		mnHoiDong.setIcon(new javax.swing.ImageIcon("image/management_60px.png")); // NOI18N
		mnHoiDong.setText("Hội đồng");
		mnHoiDong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem17ActionPerformed(evt);
			}
		});
		DanhMuc.add(mnHoiDong);

		mnKhoa.setIcon(new javax.swing.ImageIcon("image/list_60px.png")); // NOI18N
		mnKhoa.setText("Khoa");
		DanhMuc.add(mnKhoa);

		jMenuBar1.add(DanhMuc);

		mnHocKy = new JMenuItem("Học kỳ");
		mnHocKy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HocKyActionPerformed(evt);
			}
		});
		mnHocKy.setIcon(new ImageIcon("image/calendar_60px.png"));
		DanhMuc.add(mnHocKy);

		XuLy.setIcon(new javax.swing.ImageIcon("image/process_60px.png")); // NOI18N
		XuLy.setText("Xử lý");

		mnDKLV.setIcon(new javax.swing.ImageIcon("image/registration_60px.png")); // NOI18N
		mnDKLV.setText("Đăng ký luận văn");
		mnDKLV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem9ActionPerformed(evt);
			}
		});
		XuLy.add(mnDKLV);

		mnNhapDiem.setIcon(new javax.swing.ImageIcon("image/book_60px.png")); // NOI18N
		mnNhapDiem.setText("Nhập điểm");
		XuLy.add(mnNhapDiem);

		mnPhanCong.setIcon(new javax.swing.ImageIcon("image/Transfer_60px.png")); // NOI18N
		mnPhanCong.setText("Phân công hội đồng");
		XuLy.add(mnPhanCong);

		jMenuBar1.add(XuLy);

		ThongKe.setIcon(new javax.swing.ImageIcon("image/Combo Chart_60px.png")); // NOI18N
		ThongKe.setText("Thống kê");

		mnTK_Diem.setIcon(new javax.swing.ImageIcon("image/10_60px.png")); // NOI18N
		mnTK_Diem.setText("Điểm");
		ThongKe.add(mnTK_Diem);

		jMenuBar1.add(ThongKe);
		
		mntmLunVn = new JMenuItem("Luận văn");
		mntmLunVn.setIcon(new javax.swing.ImageIcon("image/Page_60px.png")); // NOI18N
		mntmLunVn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				doiManHinh(tklv_lv);
			}
		});
		ThongKe.add(mntmLunVn);

		setJMenuBar(jMenuBar1);

		pack();
	}

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		qltk_gui = new TaiKhoan_Gui();
		doiManHinh(qltk_gui);
	}

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
		doiManHinh(lv_gui);
	}

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		doiManHinh(sv_gui);
	}

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
		doiManHinh(gv_gui);
	}

	private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {
		doiManHinh(hd_gui);
	}

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
		dklv_gui = new DangKyLuanVan_Gui();
		dklv_gui.setSinhVien(sv);
		doiManHinh(dklv_gui);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor_fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor_fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	private void HocKyActionPerformed(java.awt.event.ActionEvent evt) {// GEN_FIRST:event_DangNhapActionPerformed
		hk_dialog = new HocKy_Dialog(this, rootPaneCheckingEnabled);
		hk_dialog.setTitle("Học kỳ");
		hk_dialog.setLocationRelativeTo(this);
		hk_dialog.setVisible(rootPaneCheckingEnabled);
	}

	private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN_FIRST:event_DangNhapActionPerformed
		dn_dialog = new DangNhap_Dialog(this, rootPaneCheckingEnabled);
		dn_dialog.setTitle("Đăng nhập");
		dn_dialog.setLocationRelativeTo(this);
		dn_dialog.setVisible(rootPaneCheckingEnabled);
	}

	private void DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN_FIRST:event_DoiMatKhauActionPerformed
		dmk_dialog = new DoiMatKhau_Dialog(this, rootPaneCheckingEnabled);
		dmk_dialog.setTitle("Đổi mật khẩu");
		dmk_dialog.setLocationRelativeTo(this);
		dmk_dialog.setData(taiKhoan);
		dmk_dialog.setVisible(rootPaneCheckingEnabled);
	}

	public void khoiTao() {
		dklv_gui = new DangKyLuanVan_Gui();
		gv_gui = new GiangVien_Gui();
		hd_gui = new HoiDong_Gui();
		lv_gui = new LuanVan_Gui();
		sv_gui = new SinhVien_Gui();
		qltk_gui = new TaiKhoan_Gui();
		khoa_gui = new Khoa_Gui();
		pc_gui = new PhanCong_Gui();
		nd_gui = new NhapDiem_Gui();
		ttlv_gui = new ThongTinLuanVan_Gui();
		tklv_gui = new ThongKeDiem_Gui();
		tklv_lv = new ThongKeLuanVan_Gui();
		
		tt_gui = new ThongTin_Gui();
		
		doiManHinh(tklv_gui);
	}

	public static void doiManHinh(JPanel panel) {
		dklv_gui.setVisible(false);
		gv_gui.setVisible(false);
		hd_gui.setVisible(false);
		lv_gui.setVisible(false);
		qltk_gui.setVisible(false);
		khoa_gui.setVisible(false);
		pc_gui.setVisible(false);
		nd_gui.setVisible(false);
		sv_gui.setVisible(false);
		ttlv_gui.setVisible(false);
		tklv_gui.setVisible(false);
		tklv_lv.setVisible(false);
		tt_gui.setVisible(false);

		jPanel1.add(panel);
		panel.setVisible(true);
	}

	public static void xemThongTinLV() {
		ttlv_gui = new ThongTinLuanVan_Gui();
		ttlv_gui.setSinhVien(sv);
		doiManHinh(ttlv_gui);
	}

	public static void quayLaiDangK() {
		dklv_gui = new DangKyLuanVan_Gui();
		dklv_gui.setSinhVien(sv);
		doiManHinh(dklv_gui);
	}
	
	public static void quyenSinhVien() {
		mnDangXuat.setEnabled(true);
		mnDoiMatKhau.setEnabled(true);
		
		XuLy.setEnabled(true);
		mnDKLV.setEnabled(true);
		mnPhanCong.setEnabled(false);
		mnNhapDiem.setEnabled(false);
	}
	
	public static void quyenQuanLy() {
		mnDangXuat.setEnabled(true);
		mnDoiMatKhau.setEnabled(true);
		
		mnTaiKhoan.setEnabled(true);
		DanhMuc.setEnabled(true);
		XuLy.setEnabled(true);
		ThongKe.setEnabled(true);
		
		mnPhanCong.setEnabled(true);
		mnNhapDiem.setEnabled(true);
		mnDKLV.setEnabled(false);
	}
	
	public void dangXuat() {
		DanhMuc.setEnabled(false);
		XuLy.setEnabled(false);
		ThongKe.setEnabled(false);
		
		txtTaiKhoan.setText("");
		
		mnDangNhap.setEnabled(true);
		mnDangXuat.setEnabled(false);
		mnDoiMatKhau.setEnabled(false);
		mnTaiKhoan.setEnabled(false);
		
		doiManHinh(tt_gui);
	}

	public static void setTaiKhoan(TaiKhoan tk) {
		mnDangNhap.setEnabled(false);
		taiKhoan = tk;
		try {
			sv = qlsv.chiTietSinhVien(tk.getTenTk());
			txtTaiKhoan.setText("Tài khoản: "+ sv.getHoTen());
		} catch (Exception e) {
			txtTaiKhoan.setText("Tài khoản: Quản lý" );
		}
		if(tk.getQuyen() == 1) {
			quyenSinhVien();
		}else {
			quyenQuanLy();
		}
	}
	private gui_dialog.HocKy_Dialog hk_dialog;
	private DangNhap_Dialog dn_dialog;
	private DoiMatKhau_Dialog dmk_dialog;
	public static ThongTin_Gui tt_gui;
	public static DangKyLuanVan_Gui dklv_gui;
	public static GiangVien_Gui gv_gui;
	public static HoiDong_Gui hd_gui;
	public static LuanVan_Gui lv_gui;
	public static SinhVien_Gui sv_gui;
	public static TaiKhoan_Gui qltk_gui;
	public static Khoa_Gui khoa_gui;
	public static gui.PhanCong_Gui pc_gui;
	public static gui.NhapDiem_Gui nd_gui;
	public static ThongTinLuanVan_Gui ttlv_gui;
	public static ThongKeDiem_Gui tklv_gui;
	public static ThongKeLuanVan_Gui tklv_lv;
	// Variables declaration _ do not modify//GEN_BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private static javax.swing.JMenu DanhMuc;
	private static javax.swing.JMenu XuLy;
	private static javax.swing.JMenu ThongKe;
	private static javax.swing.JMenu HeThong;
	private javax.swing.JMenuBar jMenuBar1;
	private static javax.swing.JMenuItem mnDangNhap;
	private static javax.swing.JMenuItem mnNhapDiem;
	private javax.swing.JMenuItem mnTK_Diem;
	private javax.swing.JMenuItem mnThongTin;
	private static javax.swing.JMenuItem mnPhanCong;
	private javax.swing.JMenuItem mnKhoa;
	private javax.swing.JMenuItem mnHoiDong;
	private static javax.swing.JMenuItem mnDoiMatKhau;
	private static javax.swing.JMenuItem mnDangXuat;
	private javax.swing.JMenuItem mnThoat;
	private static javax.swing.JMenuItem mnTaiKhoan;
	private javax.swing.JMenuItem mnLuanVan;
	private javax.swing.JMenuItem mnSinhVien;
	private javax.swing.JMenuItem mnGiangVien;
	private static javax.swing.JMenuItem mnDKLV;
	private static javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private JMenuItem mnHocKy;
	
	private static JLabel txtTaiKhoan;

	private static QuanLySinhVien qlsv;
	public static TaiKhoan taiKhoan;
	public static SinhVien sv;
	private JMenuItem mntmLunVn;
}
