/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.QuanLyGiangVien;
import dao.QuanLyKhoa;
import dao.QuanLyLuanVan;
import database.Database;
import entities.GiangVien;
import entities.Khoa;
import entities.LuanVan;
import gui_dialog.Khoa_Dialog;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author nmrhu
 */
public class ThongTin_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public ThongTin_Gui() {
		setSize(new Dimension(1500, 700));
		initComponents();

		DocDuLieuDatabaseVaoTable("");
		clear();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();

		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBackground(Color.WHITE);
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();

		setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Hệ thống / Thông tin");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 344, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(1109, Short.MAX_VALUE))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		jPanel3.setLayout(jPanel3Layout);

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Khoa", "Tên khoa", "Website", "SĐT", "Email" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		
		lblVngGiaHng = new JLabel();
		lblVngGiaHng.setText("Vương Gia Hưng");
		lblVngGiaHng.setForeground(new Color(0, 153, 255));
		lblVngGiaHng.setFont(new Font("Tahoma", Font.BOLD, 24));
		
		lblTrnNhtDuy = new JLabel();
		lblTrnNhtDuy.setText("Trần Nhật Duy");
		lblTrnNhtDuy.setForeground(new Color(0, 153, 255));
		lblTrnNhtDuy.setFont(new Font("Tahoma", Font.BOLD, 24));
		
		lblLVnPhc = new JLabel();
		lblLVnPhc.setText("Lê Văn Phúc");
		lblLVnPhc.setForeground(new Color(0, 153, 255));
		lblLVnPhc.setFont(new Font("Tahoma", Font.BOLD, 24));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(
			jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addGap(128)
					.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(lblLVnPhc, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblTrnNhtDuy, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblVngGiaHng, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
					.addContainerGap(859, Short.MAX_VALUE))
		);
		jPanel4Layout.setVerticalGroup(
			jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVngGiaHng, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblTrnNhtDuy, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblLVnPhc, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(418, Short.MAX_VALUE))
		);
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1198,
										Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(18).addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	public void xoaKhoa() {
		int hoi = JOptionPane.showConfirmDialog(this,
				"Bạn có chắc chắn xóa " + khoa.getMaKhoa() + " - " + khoa.getTenKhoa() + " không ?", "Chú ý",
				JOptionPane.YES_NO_OPTION);
		if (hoi == JOptionPane.YES_OPTION) {
			try {
				qlkhoa.delete(khoa.getMaKhoa());
				DocDuLieuDatabaseVaoTable("");
				main.lv_gui.DocDuLieuDatabaseVaoCombobox();
				main.sv_gui.DocDuLieuDatabaseVaoCombobox();
				main.gv_gui.DocDuLieuDatabaseVaoCombobox();
				clear();
				JOptionPane.showMessageDialog(this, "Xóa thành công ");
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(this, "Xóa không thành công ");
			}
		}
	}

	public void DocDuLieuDatabaseVaoTable(String txt) {
		dm.setRowCount(0);
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();

		if (txt.equals(""))
			list = qlkhoa.dsKhoa();
		else {
			list = qlkhoa.tim_Khoa(txt);
		}
		if (list.size() == 0) {
			dm.setRowCount(0);
			JOptionPane.showMessageDialog(this, "Không tìm thấy");
		} else {
			for (Khoa k : list) {
				dm.addRow(new Object[] { k.getMaKhoa(), k.getTenKhoa(), k.getWebsite(), k.getSdt(), k.getemail() });
			}
		}
	}

	public void clear() {
	}
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.table.DefaultTableModel dm;

	private QuanLyKhoa qlkhoa;
	public static Main main;
	public static Khoa khoa;
	private JLabel lblVngGiaHng;
	private JLabel lblTrnNhtDuy;
	private JLabel lblLVnPhc;
	// End of variables declaration//GEN-END:variables
}
