/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import dao.QuanLyHocKy;
import dao.QuanLyKhoa;
import dao.QuanLyPhieuDangKy;
import database.Database;
import entities.HocKy;
import entities.Khoa;

import javax.swing.JComboBox;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.Font;

/**
 *
 * @author nmrhu
 */
public class ThongKeDiem_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public ThongKeDiem_Gui() {
		setSize(new Dimension(1500, 700));
		initComponents();

		DocDuLieuDatabaseVaoCombobox();
		DocDuLieuDatabaseVaoComboboxHocKy();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();
		qlhk = new QuanLyHocKy();
		qlpdk = new QuanLyPhieuDangKy();

		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		btnLoc = new javax.swing.JButton();
		btnLoc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int soLuongDK, soLV, slDat, slKDay;
				float diemTB = 0;
				try {
					soLuongDK = qlpdk.soLuongDangKy_TrongHK_Khoa(hk, k);
					soLV = qlpdk.soLuongLV_TrongHK_Khoa(hk, k);
					slDat = qlpdk.soLuongLV_Dat_TrongHK_Khoa(hk, k);
					slKDay = qlpdk.soLuongLV_KhongDat_TrongHK_Khoa(hk, k);
					diemTB = qlpdk.diemTB_TrongHK_Khoa(hk, k);

					txtSLDK.setText(soLuongDK + "");
					txtSLLV.setText(soLV + "");
					txtSLDat.setText(slDat + "");
					txtSLKDat.setText(slKDay + "");
					txtDiemTB.setText(diemTB + "");
					
					veBieuDo(hk, k);

				} catch (SQLException e1) {
					e1.printStackTrace();
				}
			}
		});
		jPanel5 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSLLV = new javax.swing.JTextField();
		txtSLLV.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSLDK = new javax.swing.JTextField();
		txtSLDK.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSLDat = new javax.swing.JTextField();
		txtSLDat.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtSLKDat = new javax.swing.JTextField();
		txtSLKDat.setFont(new Font("Tahoma", Font.PLAIN, 20));
		cbbKhoa = new javax.swing.JComboBox<>();

		setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Thống kê / Điểm luận văn");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 344, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(1109, Short.MAX_VALUE))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		jPanel3.setLayout(jPanel3Layout);

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		cbbHK_1 = new javax.swing.JComboBox<HocKy>();
		DefaultComboBoxModel<HocKy> dmHK = new DefaultComboBoxModel<HocKy>();
		cbbHK_1.setModel(dmHK);
		cbbHK_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				hk = (HocKy) cbbHK_1.getSelectedItem();
			}
		});
		btnLoc.setIcon(new javax.swing.ImageIcon("image/Mail Filter_30px.png")); // NOI18N
		btnLoc.setText("Lọc");

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Biểu đồ:"));
		jPanel5.setLayout(new java.awt.BorderLayout());

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin:"));

		jLabel2.setText("Tổng số luận văn:");

		jLabel3.setText("Tổng sinh viên đăng ký:");

		jLabel4.setText("Số lượng đạt:");

		jLabel5.setText("Số lượng không đạt");

		JLabel lblTrungBnhim = new JLabel();
		lblTrungBnhim.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblTrungBnhim.setText("Trung bình điểm:");

		txtDiemTB = new JTextField();
		txtDiemTB.setFont(new Font("Tahoma", Font.PLAIN, 20));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGap(18)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(txtSLLV, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE).addComponent(txtSLDK))
				.addGap(18)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addPreferredGap(ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addComponent(lblTrungBnhim, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
								.addGap(18)))
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false).addComponent(txtDiemTB)
						.addComponent(txtSLDat).addComponent(txtSLKDat, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
				.addContainerGap(55, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(Alignment.TRAILING).addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel4)
										.addComponent(txtSLDat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addGap(8)
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel5)
										.addComponent(txtSLKDat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2)
										.addComponent(txtSLLV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addGap(8)
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3)
										.addComponent(txtSLDK, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(lblTrungBnhim)
						.addComponent(txtDiemTB, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addGap(20)));
		jPanel2.setLayout(jPanel2Layout);

		DefaultComboBoxModel<Khoa> dmCbb = new DefaultComboBoxModel<Khoa>();
		cbbKhoa.setModel(dmCbb);
		cbbKhoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				k = (Khoa) cbbKhoa.getSelectedItem();
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(
			jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel5, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1436, Short.MAX_VALUE)
						.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1436, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
							.addGap(251)
							.addComponent(cbbHK_1, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(cbbKhoa, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnLoc, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		jPanel4Layout.setVerticalGroup(
			jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnLoc)
						.addComponent(cbbKhoa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(cbbHK_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 430, GroupLayout.PREFERRED_SIZE)
					.addGap(9))
		);
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
						.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		this.setLayout(layout);
	}

	public void XoaHetDuLieuTrenCombobox() {
		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();
		list = qlkhoa.dsKhoa();

		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		for (Khoa khoa : list) {
			dm.addElement(khoa);
		}
	}

	public void XoaHetDuLieuTrenComboboxHocKy() {
		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK_1.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxHocKy() {
		XoaHetDuLieuTrenComboboxHocKy();
		List<HocKy> list = new ArrayList<HocKy>();
		qlhk = new QuanLyHocKy();
		list = qlhk.dsHocKy();

		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK_1.getModel();
		for (HocKy hk : list) {
			dm.addElement(hk);
		}
	}

	public void veBieuDo(HocKy hk, Khoa k) {
		DefaultCategoryDataset dcd = new DefaultCategoryDataset();

		try {
			int sLT = qlpdk.soLuongDangKy_TrongHK_Khoa(hk, k);

			int soLuongDiem1 = qlpdk.soLuongDiem(hk, k, 1, 2);
			dcd.setValue(soLuongDiem1, "1", "1");

			int soLuongDiem2 = qlpdk.soLuongDiem(hk, k, 2, 3);
			dcd.setValue(soLuongDiem2, "2", "2");

			int soLuongDiem3 = qlpdk.soLuongDiem(hk, k, 3, 4);
			dcd.setValue(soLuongDiem3, "3", "3");

			int soLuongDiem4 = qlpdk.soLuongDiem(hk, k, 4, 5);
			dcd.setValue(soLuongDiem4, "4", "4");

			int soLuongDiem5 = qlpdk.soLuongDiem(hk, k, 5, 6);
			dcd.setValue(soLuongDiem5, "5", "5");

			int soLuongDiem6 = qlpdk.soLuongDiem(hk, k, 6, 7);
			dcd.setValue(soLuongDiem6, "6", "6");

			int soLuongDiem7 = qlpdk.soLuongDiem(hk, k, 7, 8);
			dcd.setValue(soLuongDiem7, "7", "7");

			int soLuongDiem8 = qlpdk.soLuongDiem(hk, k, 8, 9);
			dcd.setValue(soLuongDiem8, "8", "8");

			int soLuongDiem9 = qlpdk.soLuongDiem(hk, k, 9, 10);
			dcd.setValue(soLuongDiem9, "9", "9");

			int soLuongDiem10 = qlpdk.soLuongDiem(hk, k, 10, 11);
			dcd.setValue(soLuongDiem10, "10", "10");

			JFreeChart jchart = ChartFactory.createBarChart("", "Điểm", "Số lượng", dcd, PlotOrientation.VERTICAL,
					false, true, false);
			jchart.setBackgroundPaint(Color.WHITE);
			jchart.setTitle("Thống kê điểm khoa: " + k.getTenKhoa() + " trong học kỳ: " + hk.getTenHK());
			jchart.getTitle().setPaint(Color.BLUE);
			CategoryPlot p = jchart.getCategoryPlot();
			p.setRangeGridlinePaint(Color.GREEN);

			ChartPanel cpn = new ChartPanel(jchart);
			jPanel5.removeAll();
			jPanel5.add(cpn);
			jPanel5.updateUI();

		} catch (SQLException e) {
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLoc;
	private javax.swing.JComboBox<HocKy> cbbHK_1;
	private javax.swing.JComboBox<Khoa> cbbKhoa;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JTextField txtSLLV;
	private javax.swing.JTextField txtSLDat;
	private javax.swing.JTextField txtSLDK;
	private javax.swing.JTextField txtSLKDat;

	private QuanLyKhoa qlkhoa;
	private QuanLyHocKy qlhk;
	private QuanLyPhieuDangKy qlpdk;

	private Khoa k;
	private HocKy hk;
	private JTextField txtDiemTB;
}
