/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import dao.QuanLyChiTietHoiDong;
import dao.QuanLyChiTietPhieuDiem;
import dao.QuanLyGiangVien;
import dao.QuanLyHocKy;
import dao.QuanLyHoiDong;
import dao.QuanLyLoaiHoiDong;
import dao.QuanLyLuanVan;
import dao.QuanLyPhanCong;
import dao.QuanLyPhieuDangKy;
import dao.QuanLyPhieuDiem;
import dao.QuanLySinhVien;
import database.Database;
import entities.ChiTietPhieuDiem;
import entities.GiangVien;
import entities.HocKy;
import entities.HoiDong;
import entities.LoaiHoiDong;
import entities.LuanVan;
import entities.PhanCong;
import entities.PhieuDangKy;
import entities.PhieuDiem;
import entities.SinhVien;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.border.TitledBorder;
import javax.swing.UIManager;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;

/**
 *
 * @author nmrhu
 */
public class ThongTinLuanVan_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyTaiKhoan_Gu
	 */
	public ThongTinLuanVan_Gui() {
		setSize(new Dimension(1500, 780));
		initComponents();

		DocDuLieuDatabaseVaoComboboxHocKy();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlhk = new QuanLyHocKy();
		qllhd = new QuanLyLoaiHoiDong();
		qlhd = new QuanLyHoiDong();
		qlpdk = new QuanLyPhieuDangKy();
		qlctpd = new QuanLyChiTietPhieuDiem();
		qlpd = new QuanLyPhieuDiem();
		qllv = new QuanLyLuanVan();
		qlgv = new QuanLyGiangVien();
		qlsv = new QuanLySinhVien();
		qlpc = new QuanLyPhanCong();

		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		btnQuayLai = new javax.swing.JButton();
		btnQuayLai.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				main.quayLaiDangK();
			}
		});
		jPanel4 = new javax.swing.JPanel();
		cbbHK = new javax.swing.JComboBox<>();
		btnLoc = new javax.swing.JButton();
		btnLoc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				HocKy hk = (HocKy) cbbHK.getSelectedItem();
				setData(hk);
				DocDuLieuDatabaseVaoComboboxLHD();
				clear();
			}
		});
		jPanel5 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		cbbLHD = new javax.swing.JComboBox<>();
		cbbHD = new javax.swing.JComboBox<>();
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtNgayBao = new javax.swing.JTextField();
		txtNgayBao.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtNgayBao.setEditable(false);
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaHD = new javax.swing.JTextField();
		txtMaHD.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaHD.setEditable(false);
		txtTenLHD = new javax.swing.JTextField();
		txtTenLHD.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtTenLHD.setEditable(false);
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaLV = new javax.swing.JTextField();
		txtMaLV.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtMaLV.setEditable(false);
		txtTenLV = new javax.swing.JTextField();
		txtTenLV.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtTenLV.setEditable(false);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtGVHD = new javax.swing.JTextField();
		txtGVHD.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtGVHD.setEditable(false);
		txtDiemTB2 = new javax.swing.JTextField();
		txtDiemTB2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtDiemTB2.setEditable(false);
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 20));
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtDiemTB1 = new javax.swing.JTextField();
		txtDiemTB1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtDiemTB1.setEditable(false);
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtKetQua = new javax.swing.JTextField();
		txtKetQua.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtKetQua.setEditable(false);

		setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 153, 255));
		jLabel1.setText("Xử lý / Thông tin đăng ký");

		btnQuayLai.setBackground(new java.awt.Color(255, 255, 255));
		btnQuayLai.setIcon(new ImageIcon("image/back_arrow_30px.png")); // NOI18N
		btnQuayLai.setText("Quay lại");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnQuayLai).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										40, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnLoc.setIcon(new javax.swing.ImageIcon("image/Mail Filter_30px.png")); // NOI18N
		btnLoc.setText("Lọc");

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(new TitledBorder(null, "Chi ti\u1EBFt \u0111i\u1EC3m h\u1ED9i \u0111\u1ED3ng:",
				TitledBorder.LEADING, TitledBorder.TOP, null, null));

		dm = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Giảng viên", "Điểm" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		};
		jTable1.setModel(dm);
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setRowHeight(26);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
		jScrollPane3.setViewportView(jTable1);

		DefaultComboBoxModel<HocKy> dmHK = new DefaultComboBoxModel<HocKy>();
		cbbHK.setModel(dmHK);

		DefaultComboBoxModel<LoaiHoiDong> dmLHD = new DefaultComboBoxModel<LoaiHoiDong>();
		cbbLHD.setModel(dmLHD);
		cbbLHD.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				lhd = (LoaiHoiDong) cbbLHD.getSelectedItem();
				DocDuLieuDatabaseVaoComboboxPC(lhd, pdk);
			}
		});

		DefaultComboBoxModel<PhanCong> dmHD = new DefaultComboBoxModel<PhanCong>();
		cbbHD.setModel(dmHD);

		jLabel5.setText("Ngày báo cáo:");

		jLabel6.setText("Hội đồng:");

		jLabel7.setText("Loại hội đồng:");
		
		JLabel lblimTrungBnh = new JLabel();
		lblimTrungBnh.setFont(new Font("Tahoma", Font.PLAIN, 20));
		lblimTrungBnh.setText("Điểm trung bình:");

		txtDiemTB = new JTextField();
		txtDiemTB.setFont(new Font("Tahoma", Font.PLAIN, 20));
		txtDiemTB.setEditable(false);
		
		btnLoc2 = new javax.swing.JButton();
		btnLoc2.setIcon(new ImageIcon("image/Mail Filter_30px.png"));
		btnLoc2.setText("Lọc");
		btnLoc2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				PhanCong pc = (PhanCong) cbbHD.getSelectedItem();
				if (pc != null) {
					HoiDong hd = qlhd.chiTietHoiDong(pc.getHoiDong().getMaHD());
					LoaiHoiDong lhd = qllhd.chiTietLoaiHoiDong(hd.getLoaiHoiDong().getMaLHD());
					PhieuDiem pd = qlpd.chiTietPhieuDiem_HD_PDK(hd.getMaHD(), pdk.getMaPDK());
					DocDuLieuDatabaseVaoTable(pd.getMaPD());

					txtMaHD.setText(hd.getMaHD() + "");
					txtTenLHD.setText(lhd.getTenLHD());
					txtNgayBao.setText(pc.getNgayBaoCao() + "");

					txtDiemTB.setText(pd.getDiemTrungBinh() + "");
				} else {
					JOptionPane.showMessageDialog(null, "Không tìm thấy điểm hội đồng");
				}
			}
		});

		
		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5Layout.setHorizontalGroup(
			jPanel5Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(jPanel5Layout.createSequentialGroup()
							.addComponent(lblimTrungBnh, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
							.addGap(45)
							.addComponent(txtDiemTB))
						.addGroup(jPanel5Layout.createSequentialGroup()
							.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
								.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtNgayBao)
								.addComponent(txtTenLHD)
								.addComponent(txtMaHD, GroupLayout.PREFERRED_SIZE, 407, GroupLayout.PREFERRED_SIZE)))
						.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
							.addComponent(cbbLHD, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(cbbHD, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane3))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnLoc2, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(682, Short.MAX_VALUE))
		);
		jPanel5Layout.setVerticalGroup(
			jPanel5Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(cbbHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(cbbLHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLoc2, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel6)
						.addComponent(txtMaHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(8)
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel7)
						.addComponent(txtTenLHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel5)
						.addComponent(txtNgayBao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblimTrungBnh)
						.addComponent(txtDiemTB, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(23, Short.MAX_VALUE))
		);
		jPanel5.setLayout(jPanel5Layout);

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Luận văn"));

		jLabel2.setText("Mã luận văn:");

		jLabel3.setText("Tên luận văn");

		jLabel4.setText("Giảng viên hướng dẫn:");

		jLabel8.setText("Điểm thẩm định:");

		jLabel9.setText("Điểm báo cáo:");

		jLabel10.setText("Kết quả:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jLabel4, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel3, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtMaLV, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
								.addComponent(txtTenLV))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addComponent(txtGVHD, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)))
					.addGap(18)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(txtKetQua, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(txtDiemTB1)
							.addComponent(txtDiemTB2, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(213, Short.MAX_VALUE))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txtMaLV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(8)
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(txtTenLV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9)))
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel8)
								.addComponent(txtDiemTB1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(8)
							.addComponent(txtDiemTB2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel4)
						.addComponent(txtGVHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel10)
						.addComponent(txtKetQua, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(
			jPanel4Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 1526, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createSequentialGroup()
							.addGap(229)
							.addComponent(cbbHK, GroupLayout.PREFERRED_SIZE, 392, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnLoc, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		jPanel4Layout.setVerticalGroup(
			jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(cbbHK, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLoc))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 381, Short.MAX_VALUE)
					.addGap(9))
		);
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
	}

	public void XoaHetDuLieuTrenComboboxLHD() {
		DefaultComboBoxModel<LoaiHoiDong> dm = (DefaultComboBoxModel<LoaiHoiDong>) cbbLHD.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxLHD() {
		XoaHetDuLieuTrenComboboxLHD();
		List<LoaiHoiDong> list = new ArrayList<LoaiHoiDong>();
		qllhd = new QuanLyLoaiHoiDong();
		list = qllhd.dsLoaiHoiDong();

		DefaultComboBoxModel<LoaiHoiDong> dm = (DefaultComboBoxModel<LoaiHoiDong>) cbbLHD.getModel();
		for (LoaiHoiDong lhd : list) {
			dm.addElement(lhd);
		}
	}

	public void XoaHetDuLieuTrenComboboxPC() {
		DefaultComboBoxModel<PhanCong> dm = (DefaultComboBoxModel<PhanCong>) cbbHD.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxPC(LoaiHoiDong lhd, PhieuDangKy pdk) {
		XoaHetDuLieuTrenComboboxPC();
		List<PhanCong> list = new ArrayList<PhanCong>();
		qlpc = new QuanLyPhanCong();
		try {
			list = qlpc.dsPhanCong_SinhVien_LoaiHoiDong(pdk.getMaPDK(), lhd.getMaLHD());

			DefaultComboBoxModel<PhanCong> dm = (DefaultComboBoxModel<PhanCong>) cbbHD.getModel();
			for (PhanCong pc : list) {
				dm.addElement(pc);
			}
		} catch (Exception e) {
		}
	}

	public void XoaHetDuLieuTrenComboboxHocKy() {
		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxHocKy() {
		XoaHetDuLieuTrenComboboxHocKy();
		List<HocKy> list = new ArrayList<HocKy>();
		qlhk = new QuanLyHocKy();
		list = qlhk.dsHocKy();

		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHK.getModel();
		for (HocKy hk : list) {
			dm.addElement(hk);
		}
	}

	public void DocDuLieuDatabaseVaoTable(int maPD) {
		dm = (DefaultTableModel) jTable1.getModel();
		dm.setRowCount(0);
		List<ChiTietPhieuDiem> list = new ArrayList<ChiTietPhieuDiem>();

		list = qlctpd.tim_ChiTietPhieuDiem_PD(maPD);
		for (ChiTietPhieuDiem ctpd : list) {
			GiangVien gv = qlgv.chiTietGiangVien(ctpd.getChiTietHoiDong().getGiangVien().getMaGV());
			dm.addRow(new Object[] { gv.getHoTen(), ctpd.getDiem() });
		}
	}

	public static void setSinhVien(SinhVien sv_sql) {
		sv = sv_sql;
	}

	public void setData(HocKy hk) {
		try {
			pdk = qlpdk.chiTietPhieuDangKy_SinhVien_TrongHocKy(sv.getMaSV(), hk.getMaHK());

			LuanVan lv = qllv.chiTietLuanVan(pdk.getLuanVan().getMaLV());
			GiangVien gv = qlgv.chiTietGiangVien(lv.getGiangVien().getMaGV());
			txtMaLV.setText(lv.getMaLV() + "");
			txtTenLV.setText(lv.getTenLV());
			txtGVHD.setText(gv.getHoTen());
			if (pdk.getDiemTBVong1() == 0)
				txtDiemTB1.setText("");
			else
				txtDiemTB1.setText(pdk.getDiemTBVong1() + "");

			if (pdk.getDiemTBVong2() == 0)
				txtDiemTB2.setText("");
			else
				txtDiemTB2.setText(pdk.getDiemTBVong2() + "");

			if(txtDiemTB1.getText().equals("") || txtDiemTB2.getText().equals(""))
				txtKetQua.setText("");			
			else if (pdk.getKetQua() == 1)
				txtKetQua.setText("Đạt");
			else
				txtKetQua.setText("Không đạt");
		} catch (Exception e) {
			txtMaLV.setText("");
			txtTenLV.setText("");
			txtGVHD.setText("");
			txtDiemTB.setText("");
			txtDiemTB1.setText("");
			txtDiemTB2.setText("");
			txtKetQua.setText("");
		}

	}

	public void clear() {
		txtMaHD.setText("");
		txtTenLHD.setText("");
		txtNgayBao.setText("");
		txtDiemTB.setText("");
		
		dm.setRowCount(0);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLoc;
	private javax.swing.JButton btnLoc2;
	private javax.swing.JButton btnQuayLai;
	private javax.swing.JComboBox<PhanCong> cbbHD;
	private javax.swing.JComboBox<HocKy> cbbHK;
	private javax.swing.JComboBox<LoaiHoiDong> cbbLHD;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable1;
	private static javax.swing.JTextField txtDiemTB1;
	private static javax.swing.JTextField txtDiemTB2;
	private static javax.swing.JTextField txtGVHD;
	private static javax.swing.JTextField txtKetQua;
	private javax.swing.JTextField txtMaHD;
	private static javax.swing.JTextField txtMaLV;
	private javax.swing.JTextField txtNgayBao;
	private javax.swing.JTextField txtTenLHD;
	private static javax.swing.JTextField txtTenLV;
	private javax.swing.table.DefaultTableModel dm;

	private QuanLyHoiDong qlhd;
	private QuanLyLoaiHoiDong qllhd;
	private QuanLyHocKy qlhk;
	private static QuanLyGiangVien qlgv;
	private QuanLySinhVien qlsv;
	private static QuanLyLuanVan qllv;
	private static QuanLyPhieuDangKy qlpdk;
	private QuanLyPhieuDiem qlpd;
	private QuanLyChiTietPhieuDiem qlctpd;
	private QuanLyPhanCong qlpc;

	private LoaiHoiDong lhd;
	public static PhieuDangKy pdk;

	public static Main main;

	public static SinhVien sv;

	private JTextField txtDiemTB;
}
