package gui_dialog;

import javax.swing.JOptionPane;

import dao.QuanLyTaiKhoan;
import database.Database;
import entities.TaiKhoan;
import gui.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class DangNhap_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public DangNhap_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qltk = new QuanLyTaiKhoan();

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtTenTaiKhoan = new javax.swing.JTextField();
		txtMatKhau = new javax.swing.JTextField();
		btnDangNhap = new javax.swing.JButton();
		btnDong = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Tên đăng nhập:");

		jLabel2.setText("Mật khẩu:");

		btnDangNhap.setBackground(new java.awt.Color(0, 153, 255));
		btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
		btnDangNhap.setIcon(
				new javax.swing.ImageIcon("image/login_30px.png")); // NOI18N
		btnDangNhap.setText("Đăng nhập");
		btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dangNhap();
			}
		});

		btnDong.setBackground(new java.awt.Color(255, 0, 0));
		btnDong.setForeground(new java.awt.Color(255, 255, 255));
		btnDong.setIcon(
				new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
		btnDong.setText("Đóng");
		btnDong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dispose();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 333,
												Short.MAX_VALUE)
										.addComponent(txtMatKhau))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
												Short.MAX_VALUE)
										.addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(18, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnDangNhap).addComponent(btnDong))
				.addContainerGap(35, Short.MAX_VALUE)));

		pack();
	}

	public void dangNhap() {
		if (kiemTraNhap()) {
			String tenTK = txtTenTaiKhoan.getText();
			try {
				TaiKhoan tk = qltk.chiTietTaiKhoan(tenTK);
				String matKhau = txtMatKhau.getText();
				if(tk.getMatKhau().equals(matKhau)) {
					main.setTaiKhoan(tk);
					JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
					dispose();					
				}else {
					JOptionPane.showMessageDialog(this, "Mật khẩu không hợp lệ");
					txtMatKhau.requestFocus();
				}
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Tài khoản không hợp lệ");
				txtTenTaiKhoan.requestFocus();
			}
		}
	}

	public boolean kiemTraNhap() {
		if (txtTenTaiKhoan.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Nhập tài khoản");
			txtTenTaiKhoan.requestFocus();
			return false;
		}
		if (txtMatKhau.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Nhập mật khẩu");
			txtMatKhau.requestFocus();
			return false;
		}
		return true;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDangNhap;
	private javax.swing.JButton btnDong;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtMatKhau;
	private javax.swing.JTextField txtTenTaiKhoan;

	private QuanLyTaiKhoan qltk;
	
	public static Main main;

	// End of variables declaration//GEN-END:variables
}
