package gui_dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import dao.QuanLyGiangVien;
import dao.QuanLyKhoa;
import dao.QuanLySinhVien;
import dao.QuanLyTaiKhoan;
import database.Database;
import entities.GiangVien;
import entities.Khoa;
import entities.SinhVien;
import entities.TaiKhoan;
import gui.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class GiangVien_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public GiangVien_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();
		qlgv = new QuanLyGiangVien();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtMaGV.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});
        
        txtHoTen = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbKhoa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
		radNam.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				getRad(radNam);
				gioiTinh = 1;
			}
		});
		radNam.setSelected(true);

		radNu = new javax.swing.JRadioButton();
		radNu.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				getRad(radNu);
				gioiTinh = 0;
			}
		});

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã giảng viên:");

        jLabel2.setText("Họ tên:");

        btnLuu.setBackground(new java.awt.Color(0, 153, 255));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon("image/save_30px.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	if (quyen == 1)
					themGiangVien();
				else
					capNhatGiangVien();
            }
        });

        btnDong.setBackground(new java.awt.Color(255, 0, 0));
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

        jLabel3.setText("SDT:");

        jLabel4.setText("Email:");

        jLabel5.setText("Khoa:");

        DefaultComboBoxModel<Khoa> dmKhoa = new DefaultComboBoxModel<Khoa>();
		cbbKhoa.setModel(dmKhoa);
        cbbKhoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				khoa = (Khoa) cbbKhoa.getSelectedItem();
			}
		});
        
        jLabel6.setText("Giới tính:");

        radNam.setText("Nam");

        radNu.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaGV, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                .addComponent(txtHoTen)
                                .addComponent(cbbKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radNam, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radNu)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNam)
                    .addComponent(radNu)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    public void setData(int quyenData, GiangVien gv) {
		// quyen == 1 -> Thêm sinh viên
		DocDuLieuDatabaseVaoCombobox();
		if (quyenData == 1) {
			quyen = 1;
		}
		// -> Cập nhật sinh viên
		else {
			quyen = 2;
			setGiangVien(gv);
			txtMaGV.setEditable(false);
		}
	}

	public void setGiangVien(GiangVien gv) {
		txtMaGV.setText(gv.getMaGV());
		txtHoTen.setText(gv.getHoTen());
		Khoa k = qlkhoa.chiTietKhoa(gv.getKhoa().getMaKhoa());
		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dm.setSelectedItem(k);
		if(gv.getGioiTinh() == 0)
			getRad(radNu);
		else
			getRad(radNam);
		txtSDT.setText(gv.getSdt());
		txtEmail.setText(gv.getEmail());
	}

	public void getRad(JRadioButton rad) {
		radNam.setSelected(false);
		radNu.setSelected(false);

		rad.setSelected(true);
	}

	public void XoaHetDuLieuTrenCombobox() {
		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();
		list = qlkhoa.dsKhoa();

		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		for (Khoa khoa : list) {
			dm.addElement(khoa);
		}
	}

	public boolean kiemTraNhap() {
		String maGV = txtMaGV.getText();
		String hoTen = txtHoTen.getText();
		String sdt = txtSDT.getText();
		String email = txtEmail.getText();
		
		if(maGV.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ");
			return false;
		}
		
		if(maGV.length() != 8 ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập mã giảng viên với 8 chữ số (VD: 17039181)");
			txtMaGV.requestFocus();
			return false;
		}
		if(hoTen.equals("") ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên");
			txtHoTen.requestFocus();
			return false;
		}
		if(sdt.length() != 10) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập sdt với 10 chữ số");
			txtSDT.requestFocus();
			return false;
		}
		if(email.equals("") ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập email");
			txtEmail.requestFocus();
			return false;
		}	
		return true;
	}
	
	public void themGiangVien() {
		if(kiemTraNhap()) {
			try {
				qlgv.themGiangVien(getGiangVien());
				main.gv_gui.DocDuLieuDatabaseVaoTable("", 0, null);
				main.gv_gui.clear();
				JOptionPane.showMessageDialog(this, "Thêm giảng viên thành công!");
				clear();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Mã giảng viên đã có. Thêm giảng viên không thành công!");
				txtMaGV.requestFocus();
			}
		}
	}
	
	public void capNhatGiangVien() {
		if(kiemTraNhap()) {
			try {
				qlgv.capNhatGiangVien(getGiangVien());
				main.gv_gui.DocDuLieuDatabaseVaoTable("", 0, null);
				main.gv_gui.clear();
				main.lv_gui.DocDuLieuDatabaseVaoTable("", 0, null,null);
				main.lv_gui.clear();
				JOptionPane.showMessageDialog(this, "Cập nhật giảng viên thành công!");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Cập nhật giảng viên không thành công!");
			}
		}
	}

	public GiangVien getGiangVien() {
		String maGV = txtMaGV.getText();
		String hoTen = txtHoTen.getText();
		String sdt = txtSDT.getText();
		String email = txtEmail.getText();
		GiangVien gv = new GiangVien(maGV, hoTen, gioiTinh, sdt, email, khoa);
		return gv;
	}

	
	public void clear() {
		txtMaGV.setText("");
		txtHoTen.setText("");
		txtSDT.setText("");
		txtEmail.setText("");
		getRad(radNam);
		gioiTinh = 1;
		DocDuLieuDatabaseVaoCombobox();
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnDong;
    private javax.swing.JComboBox<Khoa> cbbKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
    
    private int quyen;
	private int gioiTinh = 1;
	private Khoa khoa;

	private QuanLyGiangVien qlgv;
	private QuanLyTaiKhoan qltk;
	private QuanLyKhoa qlkhoa;

	public static Main main;
}
