package gui_dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import dao.QuanLyHocKy;
import database.Database;
import entities.HocKy;
import gui.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class HocKy_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public HocKy_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        DocDuLieuDatabaseVaoCombobox();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this cod3e. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
    	qlhk = new QuanLyHocKy();

        btnDong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaHK = new javax.swing.JTextField();
        txtMaHK.setEditable(false);
        txtTenHK = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radHK_HienTai = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnDong.setBackground(new java.awt.Color(255, 0, 0));
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });

        jLabel2.setText("Tên học kỳ:");

        btnLuu.setBackground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon("image/add_30px.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String tenHK = txtTenHK.getText();
        		if(tenHK.equals("")) {
        			JOptionPane.showMessageDialog(null, "Vui lòng nhập tên học kỳ");
        		}else {
        			HocKy hk_moi = new HocKy(tenHK,0);
        			try {
						qlhk.themHocKy(hk_moi);
	        			DocDuLieuDatabaseVaoCombobox();
	        			JOptionPane.showMessageDialog(null, "Thêm học kỳ thành công");
	        			clear();
					} catch (Exception e1) {
	        			JOptionPane.showMessageDialog(null, "Thêm học kỳ không thành công");
					}
        		}
        	}
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
					qlhk.delete(Integer.parseInt(txtMaHK.getText()));
	        		DocDuLieuDatabaseVaoCombobox();
					JOptionPane.showMessageDialog(null, "Xóa học kỳ thành công!");
					clear();
	        		txtMaHK.setText("");
	        		txtTenHK.setText("");
				} catch (Exception e1) {
					JOptionPane.showMessageDialog(null, "Học kỳ không thể xóa!");
				}
        	}
        });

        btnThemMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setIcon(new javax.swing.ImageIcon("image/new_30px.png")); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int maHK = qlhk.getmaHK();
        		txtMaHK.setText(""+maHK);
        		txtTenHK.setText("");
        		
        		btnXoa.setEnabled(false);
        		btnLuu.setEnabled(true);
        	}
        });
        

        jLabel1.setText("Mã học kỳ:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã học kỳ", "Tên học kỳ"}) {
			boolean[] canEdit = new boolean[] { false, false ,false};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				int row = jTable1.getSelectedRow();
				TableModel model = jTable1.getModel();
				String maHK = model.getValueAt(row, 0).toString();
				String tenHK = model.getValueAt(row, 1).toString();
				txtMaHK.setText(maHK);
				txtTenHK.setText(tenHK);
				btnXoa.setEnabled(true);
			}
		});
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setRowHeight(22);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 22));
		jScrollPane1.setViewportView(jTable1);

        radHK_HienTai.setText("Học kỳ hiện tại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenHK)
                                .addComponent(txtMaHK, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radHK_HienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radHK_HienTai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnThemMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDong)
                .addGap(26, 26, 26))
        );

        pack();
    }
    
    public void XoaHetDuLieuTrenCombobox() {
    	DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
		dm.getDataVector().removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<HocKy> list = new ArrayList<HocKy>();
		qlhk = new QuanLyHocKy();
		list = qlhk.dsHocKy();

		DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
		for (HocKy hocKy : list) {
			dm.addRow(new Object[] {hocKy.getMaHK(),hocKy.getTenHK()});
		}
	}
    
	
	public void clear() {
		btnLuu.setEnabled(false);
		btnXoa.setEnabled(false);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radHK_HienTai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTenHK;
    private javax.swing.JTextField txtMaHK;
    
    private QuanLyHocKy qlhk;
    private HocKy hk;
    
    public static Main main;
    // End of variables declaration//GEN-END:variables
}
