package gui_dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import dao.QuanLyGiangVien;
import dao.QuanLyKhoa;
import dao.QuanLyLuanVan;
import database.Database;
import entities.GiangVien;
import entities.Khoa;
import entities.LuanVan;
import gui.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class Khoa_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Khoa_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhoa = new javax.swing.JTextField();
        txtMaKhoa.setEditable(false);
        txtTenKhoa = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã khoa:");

        jLabel2.setText("Tên khoa:");

        btnLuu.setBackground(new java.awt.Color(0, 153, 255));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon("image/save_30px.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	if (quyen == 1)
					themKhoa();
				else
					capNhatKhoa();
            }
        });

        btnDong.setBackground(new java.awt.Color(255, 0, 0));
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

        jLabel3.setText("Website:");

        jLabel4.setText("SDT:");

        jLabel7.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txtTenKhoa))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtWebsite)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    public void setData(int quyenData, Khoa k) {
		// quyen == 1 -> Thêm sinh viên
		if (quyenData == 1) {
			quyen = 1;
			int maLV;
			try {
				maLV = qlkhoa.getMakhoa();
			} catch (Exception e) {
				maLV = 0;
			}
			txtMaKhoa.setText(""+maLV);
		}
		// -> Cập nhật sinh viên
		else {
			quyen = 2;
			setKhoa(k);
		}
	}

	public void setKhoa(Khoa k) {
		txtMaKhoa.setText(""+k.getMaKhoa());
		txtTenKhoa.setText(k.getTenKhoa());
		txtWebsite.setText(k.getWebsite());
		txtSDT.setText(k.getSdt());
		txtEmail.setText(k.getemail());
	}
	
	public boolean kiemTraNhap() {
		String tenKhoa = txtTenKhoa.getText();
		String website = txtWebsite.getText();
		String sdt = txtSDT.getText();
		String email = txtEmail.getText();
		
		if(tenKhoa.equals("") ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khoa");
			txtTenKhoa.requestFocus();
			return false;
		}
		if(website.equals("") ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập website");
			txtWebsite.requestFocus();
			return false;
		}	
		if(sdt.length() != 10 ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập SĐT 10 số");
			txtSDT.requestFocus();
			return false;
		}	
		if(email.equals("") ) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập email");
			txtEmail.requestFocus();
			return false;
		}	
		return true;
	}
	
	public Khoa getKhoa() {
		int maKhoa = Integer.parseInt(txtMaKhoa.getText());
		String tenKhoa = txtTenKhoa.getText();
		String website = txtWebsite.getText();
		String sdt = txtSDT.getText();
		String email = txtEmail.getText();
		Khoa k = new Khoa(maKhoa, tenKhoa, website, sdt, email);
		return k;
	}

	public void themKhoa() {
		if(kiemTraNhap()) {
			Khoa k = getKhoa();
			try {
				qlkhoa.themKhoa(k);
				main.khoa_gui.DocDuLieuDatabaseVaoTable("");
				main.khoa_gui.clear();
				main.lv_gui.DocDuLieuDatabaseVaoCombobox();
				main.sv_gui.DocDuLieuDatabaseVaoCombobox();
				main.gv_gui.DocDuLieuDatabaseVaoCombobox();
				JOptionPane.showMessageDialog(this, "Thêm khoa thành công!");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Thêm khoa không --- thành công!");
			}
			clear();
		}
	}
	
	public void capNhatKhoa() {
		if(kiemTraNhap()) {
			Khoa k = getKhoa();
			try {
				qlkhoa.capNhatKhoa(k);
				main.khoa_gui.DocDuLieuDatabaseVaoTable("");
				main.khoa_gui.clear();
				main.lv_gui.DocDuLieuDatabaseVaoCombobox();
				main.sv_gui.DocDuLieuDatabaseVaoCombobox();
				main.gv_gui.DocDuLieuDatabaseVaoCombobox();
				JOptionPane.showMessageDialog(this, "Cập nhật khoa thành công!");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Cập nhật khoa không thành công!");
			}
		}
	}

	public void clear() {
		int maKhoa;
		try {
			maKhoa = qlkhoa.getMakhoa();
		} catch (Exception e) {
			maKhoa = 0;
		}
		txtMaKhoa.setText(""+maKhoa);
		txtTenKhoa.setText("");
		txtWebsite.setText("");
		txtSDT.setText("");
		txtEmail.setText("");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtTenKhoa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKhoa;
    private javax.swing.JTextField txtWebsite;
    
    private int quyen;
	private QuanLyKhoa qlkhoa;
	
	public static Main main;
    // End of variables declaration//GEN-END:variables
}
