package gui_dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import database.Database;
import entities.GiangVien;
import entities.HocKy;
import entities.Khoa;
import entities.LuanVan;
import entities.SinhVien;
import entities.TaiKhoan;
import gui.Main;

import java.awt.Dimension;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import dao.QuanLyGiangVien;
import dao.QuanLyHocKy;
import dao.QuanLyKhoa;
import dao.QuanLyLuanVan;
import dao.QuanLyPhieuDangKy;
import dao.QuanLySinhVien;
import dao.QuanLyTaiKhoan;

import javax.swing.JLabel;
import javax.swing.JComboBox;
import java.awt.SystemColor;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class LuanVan_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public LuanVan_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		initComponents();

		DocDuLieuDatabaseVaoComboboxHK();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkhoa = new QuanLyKhoa();
		qlgv = new QuanLyGiangVien();
		qllv = new QuanLyLuanVan();
		qlhk = new QuanLyHocKy();
		qlpdk = new QuanLyPhieuDangKy();

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtMaLV = new javax.swing.JTextField();
		txtTenLV = new javax.swing.JTextField();
		btnLuu = new javax.swing.JButton();
		btnDong = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtSoLuongDK = new javax.swing.JTextField();
		txtSoLuongDK.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});
		jLabel5 = new javax.swing.JLabel();
		cbbKhoa = new javax.swing.JComboBox<>();
		cbbKhoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				khoa = (Khoa) cbbKhoa.getSelectedItem();
				DocDuLieuDatabaseVaoComboboxGV(khoa);
			}
		});
		cbbGiangVien = new javax.swing.JComboBox<>();
		cbbGiangVien.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				gv = (GiangVien) cbbGiangVien.getSelectedItem();
			}
		});

		setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Mã luận văn:");

		jLabel2.setText("Tên luân văn:");

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(new javax.swing.ImageIcon("image/save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (quyen == 1)
					themLuanVan();
				else
					capNhatLuanVan();
			}
		});

		btnDong.setBackground(new java.awt.Color(255, 0, 0));
		btnDong.setForeground(new java.awt.Color(255, 255, 255));
		btnDong.setIcon(new javax.swing.ImageIcon("image/delete_30px.png")); // NOI18N
		btnDong.setText("Đóng");
		btnDong.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

		txtMaLV.setEditable(false);

		jLabel3.setText("Giảng viên:");

		jLabel4.setText("Số lượng đăng ký:");

		jLabel5.setText("Khoa:");

		DefaultComboBoxModel<Khoa> dmKhoa = new DefaultComboBoxModel<Khoa>();
		cbbKhoa.setModel(dmKhoa);

		DefaultComboBoxModel<GiangVien> dmGV = new DefaultComboBoxModel<GiangVien>();
		cbbGiangVien.setModel(dmGV);

		JLabel jLabel3_1 = new JLabel();
		jLabel3_1.setText("Học kỳ");

		cbbHocKy = new JComboBox<HocKy>();
		DefaultComboBoxModel<HocKy> dmHK = new DefaultComboBoxModel<HocKy>();
		cbbHocKy.setModel(dmHK);
		cbbHocKy.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				hocKy = (HocKy) cbbHocKy.getSelectedItem();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
												.addPreferredGap(ComponentPlacement.UNRELATED))
										.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(jLabel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 139,
														Short.MAX_VALUE)
												.addComponent(jLabel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(layout
										.createSequentialGroup()
										.addComponent(
												jLabel3_1, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
										.addGap(42)))
						.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addPreferredGap(ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(txtMaLV, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
												.addComponent(txtTenLV)
												.addComponent(cbbKhoa, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(cbbGiangVien, 0, 333, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addComponent(btnLuu, GroupLayout.PREFERRED_SIZE, 154,
																GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED, 29,
																Short.MAX_VALUE)
														.addComponent(btnDong, GroupLayout.PREFERRED_SIZE, 150,
																GroupLayout.PREFERRED_SIZE))
												.addComponent(txtSoLuongDK, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
														333, Short.MAX_VALUE)))
								.addGap(357)).addGroup(
										layout.createSequentialGroup()
												.addComponent(cbbHocKy, GroupLayout.PREFERRED_SIZE, 333,
														GroupLayout.PREFERRED_SIZE)
												.addContainerGap(357, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel1).addComponent(txtMaLV,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2).addComponent(txtTenLV,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel5).addComponent(cbbKhoa,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3).addComponent(
						cbbGiangVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3_1).addComponent(cbbHocKy,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
						ComponentPlacement.UNRELATED)
				.addGroup(
						layout.createParallelGroup(Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addComponent(txtSoLuongDK, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(Alignment.BASELINE)
														.addComponent(btnDong).addComponent(btnLuu)))
								.addComponent(jLabel4))
				.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}

	public void setData(int quyenData, LuanVan lv) {
		// quyen == 1 -> Thêm sinh viên
		DocDuLieuDatabaseVaoCombobox();
		if (quyenData == 1) {
			quyen = 1;
			int maLV;
			try {
				maLV = qllv.getmaLV();
			} catch (Exception e) {
				maLV = 0;
			}
			txtMaLV.setText("" + maLV);
		}
		// -> Cập nhật sinh viên
		else {
			quyen = 2;
			setLuanVan(lv);
		}
	}

	public void setLuanVan(LuanVan lv) {
		txtMaLV.setText("" + lv.getMaLV());
		txtTenLV.setText(lv.getTenLV());
		txtSoLuongDK.setText("" + lv.getSoLuongDk());
		Khoa k = qlkhoa.chiTietKhoa(lv.getKhoa().getMaKhoa());
		DefaultComboBoxModel<Khoa> dmKhoa = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dmKhoa.setSelectedItem(k);

		GiangVien gv = qlgv.chiTietGiangVien(lv.getGiangVien().getMaGV());
		DefaultComboBoxModel<GiangVien> dmGV = (DefaultComboBoxModel<GiangVien>) cbbGiangVien.getModel();
		dmGV.setSelectedItem(gv);

		HocKy hk = qlhk.chiTietHocKy(lv.getHocKy().getMaHK());
		DefaultComboBoxModel<HocKy> dmHK = (DefaultComboBoxModel<HocKy>) cbbHocKy.getModel();
		dmHK.setSelectedItem(hk);

	}

	public void XoaHetDuLieuTrenCombobox() {
		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoCombobox() {
		XoaHetDuLieuTrenCombobox();
		List<Khoa> list = new ArrayList<Khoa>();
		qlkhoa = new QuanLyKhoa();
		list = qlkhoa.dsKhoa();

		DefaultComboBoxModel<Khoa> dm = (DefaultComboBoxModel<Khoa>) cbbKhoa.getModel();
		for (Khoa khoa : list) {
			dm.addElement(khoa);
		}
	}

	public void XoaHetDuLieuTrenComboboxGV() {
		DefaultComboBoxModel<GiangVien> dm = (DefaultComboBoxModel<GiangVien>) cbbGiangVien.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxGV(Khoa k) {
		XoaHetDuLieuTrenComboboxGV();
		List<GiangVien> list = new ArrayList<GiangVien>();
		qlgv = new QuanLyGiangVien();
		list = qlgv.tim_GiangVienTheoKhoa(k.getMaKhoa());

		DefaultComboBoxModel<GiangVien> dm = (DefaultComboBoxModel<GiangVien>) cbbGiangVien.getModel();
		for (GiangVien gv : list) {
			dm.addElement(gv);
		}
	}

	public void XoaHetDuLieuTrenComboboxHK() {
		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHocKy.getModel();
		dm.removeAllElements();
	}

	public void DocDuLieuDatabaseVaoComboboxHK() {
		XoaHetDuLieuTrenComboboxGV();
		List<HocKy> list = new ArrayList<HocKy>();
		qlhk = new QuanLyHocKy();
		list = qlhk.dsHocKy();

		DefaultComboBoxModel<HocKy> dm = (DefaultComboBoxModel<HocKy>) cbbHocKy.getModel();
		for (HocKy hk : list) {
			dm.addElement(hk);
		}
	}

	public boolean kiemTraNhap() {
		String tenLV = txtTenLV.getText();
		String soLuong = txtSoLuongDK.getText();

		if (tenLV.equals("") || soLuong.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ");
			return false;
		}
		if (tenLV.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập tên luận văn");
			txtTenLV.requestFocus();
			return false;
		}
		if (soLuong.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng đăng ký");
			txtSoLuongDK.requestFocus();
			return false;
		}
		return true;
	}

	public LuanVan getLuanVan() {
		int maLV = Integer.parseInt(txtMaLV.getText());
		String tenLV = txtTenLV.getText();
		int soLuong = Integer.parseInt(txtSoLuongDK.getText());
		LuanVan lv = new LuanVan(maLV, tenLV, gv, khoa, soLuong, hocKy);
		return lv;
	}

	public void themLuanVan() {
		if (kiemTraNhap()) {
			LuanVan lv = getLuanVan();
			try {
				qllv.themLuanVan(lv);
				main.lv_gui.DocDuLieuDatabaseVaoTable("", 0, null, null);
				main.lv_gui.clear();
				JOptionPane.showMessageDialog(this, "Thêm luận văn thành công!");
				clear();
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "Thêm luận văn không --- thành công!");
			}
		}
	}

	public void capNhatLuanVan() {
		if (kiemTraNhap()) {
			LuanVan lv = getLuanVan();
			try {
				int soLuong = qlpdk.demSoDK_LuanVan(lv);
				if (lv.getSoLuongDk() >= soLuong) {

					qllv.capNhatLuanVan(lv);
					main.lv_gui.DocDuLieuDatabaseVaoTable("", 0, null, null);
					main.lv_gui.clear();
					JOptionPane.showMessageDialog(this, "Cập nhật luận văn thành công!");
				}else {
					JOptionPane.showMessageDialog(this, "Luận văn đã có "+ soLuong +" sinh viên đăng ký nên không thể thay đổi số lượng ít hơn");
				}
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "Cập nhật luận văn không thành công!");
			}
		}
	}

	public void clear() {
		int maLV;
		try {
			maLV = qllv.getmaLV();
		} catch (Exception e) {
			maLV = 0;
		}
		txtMaLV.setText("" + maLV);
		txtTenLV.setText("");
		txtSoLuongDK.setText("");
//		DocDuLieuDatabaseVaoCombobox();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLuu;
	private javax.swing.JButton btnDong;
	private javax.swing.JComboBox<Khoa> cbbKhoa;
	private javax.swing.JComboBox<GiangVien> cbbGiangVien;
	private javax.swing.JComboBox<HocKy> cbbHocKy;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField txtTenLV;
	private javax.swing.JTextField txtSoLuongDK;
	private javax.swing.JTextField txtMaLV;

	private int quyen;

	private QuanLyGiangVien qlgv;
	private QuanLyLuanVan qllv;
	private QuanLyKhoa qlkhoa;
	private QuanLyHocKy qlhk;
	private QuanLyPhieuDangKy qlpdk;

	private Khoa khoa;
	private GiangVien gv;
	private HocKy hocKy;

	public static Main main;
}
